"""Row-level security configuration as idempotent DDL (RX-47, RX-48).

WHY THIS IS HAND-WRITTEN AND NOT AUTOGENERATED.

Alembic's autogenerate compares SQLAlchemy metadata against the database. RLS,
`FORCE ROW LEVEL SECURITY`, policies and privileges are not expressible in that
metadata, so autogenerate produces NONE of them - and, worse, it reports no
difference, so an operator reviewing a generated revision sees a clean diff for a
database whose isolation has been switched off. Every statement below is written
by hand for that reason.

WHY ONE FUNCTION SERVES BOTH THE MIGRATION AND THE REPAIR PATH.

The baseline migration applies these statements, and
`retrace_api.db.migrate.repair_security_configuration` re-applies them when a
database at head has drifted (a policy dropped by hand during an incident, FORCE
turned off to debug something and never turned back on). If the repair path held
its own copy of the DDL, the two could disagree and the repair would quietly
install a WEAKER configuration than the migration does. There is one source, so
they cannot.

Every statement is idempotent: `ENABLE`/`FORCE` are already idempotent, and the
policies are dropped with `IF EXISTS` before being recreated. Re-running the set
is therefore safe, which is what makes forward repair a usable recovery route
instead of a destructive downgrade.

WHY THE POLICY APPLIES TO PUBLIC RATHER THAN TO A NAMED ROLE.

`CREATE POLICY` without a `TO` clause applies to PUBLIC, which is what
`infra/sql/001_tenancy.sql` already established. Naming the service role instead
would exempt every other role, including the owner - and the owner is exactly the
identity that `FORCE ROW LEVEL SECURITY` exists to subject to the policy. A
superuser is still exempt by design, which is why the runtime identity must not
be one; that is asserted separately in `tests/migrations/test_role_attributes.py`.
"""

from __future__ import annotations

from collections.abc import Sequence

from sqlalchemy import Connection, text

__all__ = [
    "POLICY_NAME",
    "POLICY_PREDICATE",
    "REALISED_POLICY_PREDICATE",
    "SECURED_TABLES",
    "TENANT_SETTING",
    "apply_security_configuration",
    "security_statements",
]

#: The transaction-local setting carrying the request's tenant (RX-48). Chosen
#: with a prefix so it is a custom GUC rather than anything the server reserves.
TENANT_SETTING = "retrace.tenant_id"

#: Policy name, identical on every secured table so a sweep can assert its
#: presence by one name.
POLICY_NAME = "tenant_isolation"

#: Tables carrying `tenant_id` and therefore requiring the policy. Parent first:
#: the order is also the creation order the foreign key needs.
SECURED_TABLES: tuple[str, ...] = ("projects", "result_contracts")

#: RX-48. The predicate, exactly as the directive specifies it.
#:
#: THE `nullif` IS LOAD-BEARING, and the reason is not the obvious one. A setting
#: established with `set_config(..., is_local => true)` does not revert to NULL
#: when the transaction ends - it reverts to the EMPTY STRING. On a pooled
#: connection the next statement would therefore evaluate `''::uuid` and raise
#: `invalid_text_representation` (SQLSTATE 22P02). That still denies the data, so
#: it is not an isolation hole, but it converts an ordinary "no tenant context
#: set" request from a clean empty result into a hard error on a perfectly
#: normal code path - and an error that looks like a bug invites someone to
#: "fix" it by loosening the policy. With the `nullif`, an unset or emptied
#: context yields NULL, `tenant_id = NULL` is NULL, and the policy matches no
#: rows: it FAILS CLOSED and quietly.
#:
#: SQLite cannot exhibit any of this, which is why the proof has to run against
#: real PostgreSQL.
POLICY_PREDICATE = "tenant_id = nullif(current_setting('retrace.tenant_id', true), '')::uuid"

#: The same predicate as PostgreSQL deparses it back out of `pg_policies`.
#: Pinned so the catalogue inspection can assert the REALISED predicate rather
#: than trusting the text that was sent. Determined by reading the catalogue of
#: an applied schema on PostgreSQL 17, not copied from documentation. A future
#: server that deparses differently must fail this assertion loudly rather than
#: be accommodated by a looser comparison; the behavioural proof that the
#: predicate fails closed is asserted separately and does not depend on this
#: string.
REALISED_POLICY_PREDICATE = (
    "(tenant_id = (NULLIF(current_setting('retrace.tenant_id'::text, true), ''::text))::uuid)"
)


def security_statements(tables: Sequence[str] = SECURED_TABLES) -> tuple[str, ...]:
    """Return the idempotent RLS configuration for `tables`, in application order.

    Serves RX-47 and RX-48. Returned as text rather than executed so a migration
    can log exactly what it is about to apply and a test can assert the set is
    complete without a database.
    """
    out: list[str] = []
    for table in tables:
        # Identifiers come from this module's own constant, never from input.
        out.extend(
            (
                f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
                # ENABLE alone leaves the table's OWNER exempt. Without FORCE the
                # migration identity - which owns these tables - would read and
                # write across every tenant, and any isolation check run as the
                # owner would pass vacuously.
                f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY",
                f"DROP POLICY IF EXISTS {POLICY_NAME} ON {table}",
                f"CREATE POLICY {POLICY_NAME} ON {table} "
                f"USING ({POLICY_PREDICATE}) WITH CHECK ({POLICY_PREDICATE})",
            )
        )
    return tuple(out)


def apply_security_configuration(
    connection: Connection, tables: Sequence[str] = SECURED_TABLES
) -> tuple[str, ...]:
    """Apply the RLS configuration and return the statements that were executed.

    Serves RX-47 and RX-48. Requires ownership of `tables` (or superuser):
    `ALTER TABLE ... ENABLE ROW LEVEL SECURITY` and `CREATE POLICY` are
    owner-only operations, which is precisely why the runtime service role cannot
    perform them and must not hold migration credentials.

    Returns the statement list so the caller can record what it did. A repair that
    reported success without naming the statements it ran would not be evidence of
    anything.
    """
    statements = security_statements(tables)
    for statement in statements:
        connection.execute(text(statement))
    return statements
