"""ICU/CLDR-style cardinal plural selection (RX-27).

PROVENANCE - READ THIS BEFORE TRUSTING A CATEGORY
    The rules below were written from knowledge of the CLDR cardinal plural
    rules. They were NOT read from, generated by, or diffed against a pinned
    CLDR release, and no CLDR version number is stated here because none was
    consulted. They are therefore an ASSUMPTION, not a verified fact, and the
    verification owed is: pin a CLDR release, export
    ``supplemental/plurals.xml`` for the 36 declared locales, and assert this
    module's category equals CLDR's for a swept range of integers and decimals.
    Until that test exists, a category returned here is "derived", not "verified".

    ``babel`` is deliberately not imported: it is not installed in this
    environment, and adding a dependency is outside this unit's scope. The
    narrow implementation below is the honest alternative to pretending a
    locale-data library is present.

KNOWN LIMITS, stated rather than hidden
    * Operand ``e`` (compact-decimal exponent) is always 0: this package has no
      compact-decimal formatter, so the "million" ``many`` category of the
      Romance locales is reached only by a literal 1000000, 2000000, ...
    * ``float`` has no notion of "visible fraction digits". A float is read via
      ``Decimal(repr(value))``, which recovers the shortest round-trip spelling -
      usually what a caller meant, but not the same thing as a formatted string.
      Pass a ``str`` or ``Decimal`` when the trailing zeros matter (``"1.0"``
      and ``1`` are different CLDR inputs and are treated differently here).
    * CLDR range conditions (``n % 100 = 3..10``) match integer values only, per
      the CLDR plural-rule syntax. 3.5 is not "in" 3..10.
    * Ordinal rules and plural RANGES are not implemented at all.

The declared categories in ``specs/locales.json`` are the contract. If a rule
computes a category a locale does not declare, that is a BUG in one of the two -
:class:`PluralCategoryMismatch` is raised rather than silently coerced to
``other``, because coercion would hide the disagreement for as long as nobody
reads the strings.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from typing import Final

from .registry import Locale, LocaleRegistry, get_locale

__all__ = [
    "Operands",
    "PluralCategoryMismatch",
    "UnsupportedPluralLocale",
    "compute_plural_category",
    "plural_rule_name",
    "select_plural",
]


class PluralCategoryMismatch(ValueError):
    """A computed category is not declared for the locale (RX-27)."""

    def __init__(self, code: str, computed: str, declared: tuple[str, ...], value: object) -> None:
        self.code = code
        self.computed = computed
        self.declared = declared
        super().__init__(
            f"locale {code!r}: rule computed category {computed!r} for {value!r}, but "
            f"specs/locales.json declares only {list(declared)}. One of the two is wrong; "
            "this is not coerced to 'other' because that would hide the disagreement."
        )


class UnsupportedPluralLocale(NotImplementedError):
    """No rule is implemented for this locale and none can be inferred (RX-27)."""

    def __init__(self, code: str, subtag: str, declared: tuple[str, ...]) -> None:
        super().__init__(
            f"locale {code!r} (language {subtag!r}) has no implemented CLDR cardinal rule and "
            f"its declared categories {list(declared)} do not determine one. Implement the rule "
            "from a pinned CLDR release rather than guessing."
        )


@dataclass(frozen=True, slots=True)
class Operands:
    """The CLDR plural operands for one value (RX-27).

    ``n`` absolute value; ``i`` integer digits; ``v`` count of visible fraction
    digits; ``f`` visible fraction digits as an integer; ``t`` the same without
    trailing zeros; ``e`` compact-decimal exponent (always 0 here).
    """

    n: Decimal
    i: int
    v: int
    f: int
    t: int
    e: int = 0

    @classmethod
    def of(cls, value: int | float | str | Decimal) -> Operands:
        """Derive the operands from ``value`` (RX-27).

        An ``int`` has no fraction digits (``v = f = t = 0``). A ``str`` or
        ``Decimal`` keeps the fraction digits as written, including trailing
        zeros. A ``float`` is read through ``repr`` - see the module's known
        limits.
        """
        if isinstance(value, bool):  # bool is an int subclass; refuse it explicitly
            raise TypeError("a boolean is not a plural count")
        if isinstance(value, int):
            magnitude = abs(value)
            return cls(n=Decimal(magnitude), i=magnitude, v=0, f=0, t=0)
        try:
            decimal = Decimal(repr(value) if isinstance(value, float) else str(value))
        except InvalidOperation as exc:
            raise TypeError(f"{value!r} is not a usable plural count") from exc
        if not decimal.is_finite():
            raise TypeError(f"{value!r} is not a finite plural count")
        decimal = abs(decimal)
        sign, digits, exponent = decimal.as_tuple()
        del sign
        visible = -int(exponent) if isinstance(exponent, int) and exponent < 0 else 0
        integer_part = int(decimal.to_integral_value(rounding="ROUND_DOWN"))
        if visible:
            fraction_digits = "".join(str(d) for d in digits)[-visible:].rjust(visible, "0")
        else:
            fraction_digits = ""
        f = int(fraction_digits) if fraction_digits else 0
        stripped = fraction_digits.rstrip("0")
        t = int(stripped) if stripped else 0
        return cls(n=decimal, i=integer_part, v=visible, f=f, t=t)

    @property
    def is_integer(self) -> bool:
        """Whether the value has no visible fraction digits (RX-27)."""
        return self.v == 0

    def n_in(self, *values: int) -> bool:
        """CLDR ``n = a,b`` / ``n = a..b`` membership - integers only (RX-27)."""
        return self.is_integer and int(self.n) in values

    def n_mod_in(self, modulus: int, low: int, high: int) -> bool:
        """CLDR ``n % m = low..high`` membership - integers only (RX-27)."""
        return self.is_integer and low <= int(self.n) % modulus <= high


# ---------------------------------------------------------------------------
# Rule implementations. One function per CLDR rule shape actually present in
# specs/locales.json. Named after the shape, not the language, so two languages
# that share a rule share the implementation and cannot drift apart.
# ---------------------------------------------------------------------------


def _rule_other_only(_: Operands) -> str:
    """Single-category languages: zh-Hans, ja, ko, vi, th, id (RX-27)."""
    return "other"


def _rule_one_i1v0(o: Operands) -> str:
    """``one: i = 1 and v = 0`` - en, de, nl, sv, fi, sw, ur (RX-27)."""
    return "one" if o.i == 1 and o.v == 0 else "other"


def _rule_one_n1(o: Operands) -> str:
    """``one: n = 1`` - el, hu, tr, nb, ta, te (RX-27)."""
    return "one" if o.n == 1 else "other"


def _rule_one_i0_or_n1(o: Operands) -> str:
    """``one: i = 0 or n = 1`` - hi, bn, fa (RX-27)."""
    return "one" if o.i == 0 or o.n == 1 else "other"


def _rule_one_n_0_1(o: Operands) -> str:
    """``one: n = 0..1`` - ak (RX-27)."""
    return "one" if o.n_in(0, 1) else "other"


def _rule_danish(o: Operands) -> str:
    """``one: n = 1 or t != 0 and i = 0,1`` - da (RX-27)."""
    if o.n == 1 or (o.t != 0 and o.i in (0, 1)):
        return "one"
    return "other"


def _million_many(o: Operands) -> bool:
    """Shared Romance ``many``: ``e = 0 and i != 0 and i % 1000000 = 0 and v = 0``.

    This is the compact-decimal "million" category. With no compact formatter,
    ``e`` is always 0, so it is reached only by a literal multiple of 1000000
    written without fraction digits (RX-27).
    """
    return o.e == 0 and o.i != 0 and o.i % 1_000_000 == 0 and o.v == 0


def _rule_french(o: Operands) -> str:
    """``one: i = 0,1`` plus the Romance ``many`` - fr (RX-27)."""
    if o.i in (0, 1):
        return "one"
    return "many" if _million_many(o) else "other"


def _rule_portuguese(o: Operands) -> str:
    """``one: i = 0..1`` plus the Romance ``many`` - pt (RX-27)."""
    if o.i in (0, 1):
        return "one"
    return "many" if _million_many(o) else "other"


def _rule_spanish(o: Operands) -> str:
    """``one: n = 1`` plus the Romance ``many`` - es (RX-27)."""
    if o.n == 1:
        return "one"
    return "many" if _million_many(o) else "other"


def _rule_italian(o: Operands) -> str:
    """``one: i = 1 and v = 0`` plus the Romance ``many`` - it (RX-27)."""
    if o.i == 1 and o.v == 0:
        return "one"
    return "many" if _million_many(o) else "other"


def _rule_polish(o: Operands) -> str:
    """Polish four-category rule - pl (RX-27).

    ``one: i = 1 and v = 0``;
    ``few: v = 0 and i % 10 = 2..4 and i % 100 != 12..14``;
    ``many: v = 0 and (i % 10 = 0..1 or i % 10 = 5..9 or i % 100 = 12..14)``;
    everything with visible fraction digits is ``other``.
    """
    if o.v != 0:
        return "other"
    i = o.i
    if i == 1:
        return "one"
    if 2 <= i % 10 <= 4 and not 12 <= i % 100 <= 14:
        return "few"
    if i % 10 in (0, 1) or 5 <= i % 10 <= 9 or 12 <= i % 100 <= 14:
        return "many"
    return "other"


def _rule_east_slavic(o: Operands) -> str:
    """Russian/Ukrainian four-category rule - ru, uk (RX-27).

    ``one: v = 0 and i % 10 = 1 and i % 100 != 11``;
    ``few: v = 0 and i % 10 = 2..4 and i % 100 != 12..14``;
    ``many: v = 0 and (i % 10 = 0 or i % 10 = 5..9 or i % 100 = 11..14)``;
    fractions are ``other``.
    """
    if o.v != 0:
        return "other"
    i = o.i
    if i % 10 == 1 and i % 100 != 11:
        return "one"
    if 2 <= i % 10 <= 4 and not 12 <= i % 100 <= 14:
        return "few"
    if i % 10 == 0 or 5 <= i % 10 <= 9 or 11 <= i % 100 <= 14:
        return "many"
    return "other"


def _rule_west_slavic(o: Operands) -> str:
    """Czech/Slovak rule - cs, sk (RX-27).

    ``one: i = 1 and v = 0``; ``few: i = 2..4 and v = 0``; ``many: v != 0``;
    otherwise ``other``.
    """
    if o.v != 0:
        return "many"
    if o.i == 1:
        return "one"
    if 2 <= o.i <= 4:
        return "few"
    return "other"


def _rule_romanian(o: Operands) -> str:
    """Romanian rule - ro (RX-27).

    ``one: i = 1 and v = 0``;
    ``few: v != 0 or n = 0 or (n != 1 and n % 100 = 1..19)``; otherwise ``other``.
    """
    if o.i == 1 and o.v == 0:
        return "one"
    if o.v != 0 or o.n == 0 or (o.n != 1 and o.n_mod_in(100, 1, 19)):
        return "few"
    return "other"


def _rule_hebrew(o: Operands) -> str:
    """Hebrew four-category rule - he (RX-27).

    ``one: i = 1 and v = 0``; ``two: i = 2 and v = 0``;
    ``many: v = 0 and n % 10 = 0 and n not in 0..10``; otherwise ``other``.

    ASSUMPTION WITH A KNOWN DISPUTE: later CLDR releases dropped Hebrew's
    ``many`` category. ``specs/locales.json`` declares it, so the four-category
    form is implemented here. Which is right depends on the CLDR version the
    product pins - exactly the verification this module says is owed.
    """
    if o.v == 0:
        if o.i == 1:
            return "one"
        if o.i == 2:
            return "two"
        value = int(o.n)
        if value % 10 == 0 and not 0 <= value <= 10:
            return "many"
    return "other"


def _rule_arabic(o: Operands) -> str:
    """Arabic six-category rule - ar (RX-27).

    ``zero: n = 0``; ``one: n = 1``; ``two: n = 2``;
    ``few: n % 100 = 3..10``; ``many: n % 100 = 11..99``; otherwise ``other``
    (which is where 100, 101, 102 and every fractional value land).
    """
    if o.n == 0:
        return "zero"
    if o.n == 1:
        return "one"
    if o.n == 2:
        return "two"
    if o.n_mod_in(100, 3, 10):
        return "few"
    if o.n_mod_in(100, 11, 99):
        return "many"
    return "other"


#: Language subtag -> rule. Keyed on the SUBTAG, never on the full tag, so the
#: pending ``ur`` -> ``ur-PK`` reconciliation cannot change plural behaviour.
#: This is a rule table, not a locale list: it must never be read as the set of
#: supported locales - :func:`registry` is.
_RULES: Final[Mapping[str, Callable[[Operands], str]]] = {
    "ak": _rule_one_n_0_1,
    "ar": _rule_arabic,
    "bn": _rule_one_i0_or_n1,
    "cs": _rule_west_slavic,
    "da": _rule_danish,
    "de": _rule_one_i1v0,
    "el": _rule_one_n1,
    "en": _rule_one_i1v0,
    "es": _rule_spanish,
    "fa": _rule_one_i0_or_n1,
    "fi": _rule_one_i1v0,
    "fr": _rule_french,
    "he": _rule_hebrew,
    "hi": _rule_one_i0_or_n1,
    "hu": _rule_one_n1,
    "id": _rule_other_only,
    "it": _rule_italian,
    "iw": _rule_hebrew,
    "ja": _rule_other_only,
    "ko": _rule_other_only,
    "nb": _rule_one_n1,
    "nl": _rule_one_i1v0,
    "no": _rule_one_n1,
    "pl": _rule_polish,
    "pt": _rule_portuguese,
    "ro": _rule_romanian,
    "ru": _rule_east_slavic,
    "sk": _rule_west_slavic,
    "sv": _rule_one_i1v0,
    "sw": _rule_one_i1v0,
    "ta": _rule_one_n1,
    "te": _rule_one_n1,
    "th": _rule_other_only,
    "tr": _rule_one_n1,
    "uk": _rule_east_slavic,
    "ur": _rule_one_i1v0,
    "vi": _rule_other_only,
    "zh": _rule_other_only,
}


def _rule_for(locale: Locale) -> tuple[str, Callable[[Operands], str]]:
    """Return the rule name and function for ``locale`` (RX-27).

    Falls back ONLY where the declared category set determines the answer
    unambiguously: a single ``other`` category, or exactly ``one``/``other``.
    Anything richer raises rather than guessing, because guessing a Slavic or
    Semitic rule produces output that looks right and is wrong.
    """
    subtag = locale.language_subtag
    rule = _RULES.get(subtag)
    if rule is not None:
        return subtag, rule
    declared = set(locale.plural_categories)
    if declared == {"other"}:
        return "inferred:other-only", _rule_other_only
    if declared == {"one", "other"}:
        return "inferred:one-other", _rule_one_n1
    raise UnsupportedPluralLocale(locale.code, subtag, locale.plural_categories)


def plural_rule_name(code: str, *, source: LocaleRegistry | None = None) -> str:
    """Return the name of the rule used for ``code`` (RX-27).

    Exposed so a reviewer can see WHICH rule a locale got, and so the owed
    CLDR comparison can be reported per rule rather than per locale.
    """
    return _rule_for(get_locale(code, source=source))[0]


def compute_plural_category(
    code: str,
    value: int | float | str | Decimal,
    *,
    source: LocaleRegistry | None = None,
) -> str:
    """Return the raw CLDR category for ``value`` in ``code`` (RX-27).

    Does NOT check the result against the locale's declared categories. Use
    :func:`select_plural` unless you are specifically testing the rule.
    """
    _, rule = _rule_for(get_locale(code, source=source))
    return rule(Operands.of(value))


def select_plural(
    code: str,
    value: int | float | str | Decimal,
    *,
    source: LocaleRegistry | None = None,
) -> str:
    """Return the CLDR plural category for ``value`` in locale ``code`` (RX-27).

    Raises
    ------
    PluralCategoryMismatch:
        If the rule computes a category the locale does not declare. That is a
        bug in the rule or in the spec and is surfaced, not papered over.
    UnsupportedPluralLocale:
        If no rule is implemented and none can be inferred safely.
    """
    locale = get_locale(code, source=source)
    _, rule = _rule_for(locale)
    computed = rule(Operands.of(value))
    if computed not in locale.plural_categories:
        raise PluralCategoryMismatch(locale.code, computed, locale.plural_categories, value)
    return computed
